# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  api:
    build: .
    restart: always
    ports:
      - 5009:5009
    environment:
       DATABASE__CONNECTIONSTRING: "User ID=postgres;Password=awesomeUrlDabatase123;Host=localhost;Port=5432;Database=UrlShortenerDatabase;"
  